url: "https://hearthsim.info"
baseurl: ""
permalink: /blog/:title/

vars:
  name: "HearthSim"
  description: "Hearthstone Simulation & AI"
  logo: "/images/logo.png"
  email: "contact@hearthsim.info"
  hdt_download: "https://hsdecktracker.net/download/"
  google_analytics:
  rss: true

  links:
    github: HearthSim
    youtube: c/HearthstoneScience
    twitter: "@HSReplayNet"
    gitter: "https://gitter.im/HearthSim/HearthSim"
    irccloud: "https://www.irccloud.com/invite?channel=%23hearthsim&amp;hostname=irc.freenode.net&amp;port=6697&amp;ssl=1"
    webchat: "https://webchat.freenode.net/?channels=hearthsim"
    discord:
      devs: "https://discord.gg/hearthsim-devs"
      users: "https://discord.gg/hearthsim"
    reddit:
      hearthsim: "https://reddit.com/r/hearthsim"
      hsreplay: "https://reddit.com/r/hsreplay"

# Syntax highlighting
markdown: kramdown
kramdown:
  # Use Github Flavored Markdown (including triple backticks)
  input: GFM
  hard_wrap: false  # No linebreak on newlines unless explicitly specified
  syntax_highlighter: rouge
  syntax_highlighter_opts:
  # Reuse pygments syntax css class
    css_class: "highlight"

sass:
  style: :compressed

exclude:
  - CNAME
  - LICENSE
  - README.md
  - vendor/
